spring:
  application:
    name: minimal-not-a-bot
  data:
    mongodb:
      host: ${MINIMAL_BOT_DBURL}
      port: 27017
      database: posts-archive
      username: ${MINIMAL_BOT_DBUSER}
      password: ${MINIMAL_BOT_DBPW}